# Generated by Django 6.0.4 on 2026-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('poster_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
