# Generated by Django 6.0.4 on 2026-04-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fongo_user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajout_Argent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fongo_user.user')),
            ],
        ),
    ]
