# Generated by Django 6.0.4 on 2026-04-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('fongo_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajout_argent',
            name='id_stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fongo_user.user'),
        ),
    ]
