# Generated by Django 6.0.4 on 2026-05-17 18:36

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fongo_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('fongo_user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(max_length=50)),
                ('duree', models.IntegerField()),
                ('id_formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formateur')),
            ],
        ),
    ]
