# Generated by Django 6.0.4 on 2026-04-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fongo_user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fongo_user.user')),
                ('matiere', models.CharField(max_length=50)),
            ],
            bases=('fongo_user.user',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('id_formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formateur')),
            ],
        ),
    ]
