# Generated by Django 6.0.4 on 2026-04-22 23:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='formateur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
