# Generated by Django 6.0.4 on 2026-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrateur'), ('stagiaire', 'Stagiaire')], default='stagiaire', max_length=20)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
    ]
