# Generated by Django 6.0.4 on 2026-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fongo_user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/'),
        ),
    ]
